# Generated by Django 6.0.3 on 2026-03-18 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='物件標題')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='總價(元)')),
                ('address', models.CharField(max_length=255, verbose_name='詳細地址')),
                ('description', models.TextField(verbose_name='物件描述')),
                ('rooms', models.IntegerField(default=3, verbose_name='房間數')),
                ('is_sold', models.BooleanField(default=False, verbose_name='是否已售出')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='訪客姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('message', models.TextField(verbose_name='留言內容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.house', verbose_name='感興趣的物件')),
            ],
        ),
    ]
