# Generated by Django 6.0.3 on 2026-03-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_photos/', verbose_name='房屋照片'),
        ),
    ]
