# Generated by Django 6.0.3 on 2026-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='衛浴數'),
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('project', '新開案'), ('subsale', '中古屋')], default='subsale', max_length=10, verbose_name='物件類別'),
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.CharField(default='台北', max_length=100, verbose_name='區域'),
        ),
        migrations.AddField(
            model_name='house',
            name='square_feet',
            field=models.IntegerField(default=0, verbose_name='坪數/平方英尺'),
        ),
    ]
