# Generated by Django 6.0.3 on 2026-03-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_bathrooms_house_category_house_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='category',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
        migrations.AddField(
            model_name='house',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=2, verbose_name='衛浴數'),
        ),
        migrations.AlterField(
            model_name='house',
            name='square_feet',
            field=models.IntegerField(default=40, verbose_name='坪數'),
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='照片描述（例如：客廳、主臥）', max_length=200)),
                ('category', models.CharField(choices=[('project', '新開案'), ('subsale', '中古屋')], default='subsale', max_length=10, verbose_name='物件類別')),
                ('bathrooms', models.IntegerField(default=1, verbose_name='衛浴數')),
                ('square_feet', models.IntegerField(default=0, verbose_name='坪數/平方英尺')),
                ('location', models.CharField(default='台北', max_length=100, verbose_name='區域')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house')),
            ],
        ),
    ]
