# Generated by Django 6.0.3 on 2026-03-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_remove_house_category_remove_house_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
    ]
