# Generated by Django 6.0.3 on 2026-03-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_remove_house_cover_image_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='image',
            new_name='cover_image',
        ),
    ]
