# Generated by Django 6.0.3 on 2026-03-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_rename_image_house_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/covers/'),
        ),
    ]
