# Generated by Django 6.0.3 on 2026-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_alter_house_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimage',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='houseimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='houseimage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='houseimage',
            name='square_feet',
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('project', '新開案'), ('subsale', '中古屋')], default='subsale', max_length=10, verbose_name='物件類別'),
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.CharField(default='台北', max_length=100, verbose_name='區域'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/covers/', verbose_name='主圖'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to='houses/gallery/', verbose_name='上傳照片'),
        ),
    ]
