# Generated by Django 6.0.3 on 2026-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_remove_houseimage_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_starting_price',
            field=models.BooleanField(default=False, help_text='勾選後，網頁價格後方會出現『萬起』字', verbose_name='是否顯示『萬起』'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.CharField(default=2, help_text='可以填寫範圍，例如：2-3', max_length=50, verbose_name='衛浴數'),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('project', '新開案'), ('subsale', '中古屋')], default='subsale', max_length=10, verbose_name='物件狀態'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='總價 (MYR)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.CharField(default=3, help_text='可以填寫範圍，例如：1-3', max_length=50, verbose_name='房間數'),
        ),
    ]
