# Generated by Django 6.0.3 on 2026-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_house_is_starting_price_alter_house_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='總價 (RM)'),
        ),
    ]
