# Generated by Django 6.0.3 on 2026-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='is_starting_price',
            field=models.BooleanField(default=True, verbose_name='是否顯示『萬起』'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(help_text='請輸入數字範圍，例如：100-500', max_length=100, verbose_name='價格區間'),
        ),
    ]
