# Generated by Django 6.0.3 on 2026-05-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_alter_house_is_starting_price_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(help_text='勾選下方時填寫數字即可(如: 100-500)；不勾選時請填寫完整格式(如: 10000000)', max_length=100, verbose_name='價格區間'),
        ),
    ]
