# Generated by Django 6.0.3 on 2026-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('project', '新成屋'), ('subsale', '中古屋')], default='subsale', max_length=10, verbose_name='物件狀態'),
        ),
    ]
